# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mlogin < Formula
  desc "CLI for managing macOS login/background items and system extensions"
  homepage "https://github.com/j4n-e4t/mlogin"
  version "0.0.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/j4n-e4t/mlogin/releases/download/v0.0.1/mlogin_0.0.1_darwin_amd64.tar.gz"
    sha256 "0f07881c739fdfc5719b1142a7e0b7d24c996c95264fdd595aff2e37415dbe54"

    def install
      bin.install "mlogin"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/j4n-e4t/mlogin/releases/download/v0.0.1/mlogin_0.0.1_darwin_arm64.tar.gz"
    sha256 "0a5d25455d770e2657e72fa84752a5bfb3b2fdefc002d9138c3d359d6dd6212b"

    def install
      bin.install "mlogin"
    end
  end

  test do
    system "#{bin}/mlogin", "version"
  end
end
